[[plugins]] # dark powered completion
repo = 'Shougo/deoplete.nvim'
if = 'has("python3")'
depends = 'context_filetype.vim'
on_event = 'InsertEnter'
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    let g:deoplete#enable_ignore_case = 1
    " let g:deoplete#enable_smart_case = 1

    " <TAB>: completion
	inoremap <silent><expr> <TAB>
    \ pumvisible() ? "\<C-n>" :
    \ <SID>check_back_space() ? "\<TAB>" :
    \ deoplete#mappings#manual_complete()
    function! s:check_back_space() abort "{{{
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~ '\s'
    endfunction"}}}
 "
    " <S-TAB>: completion back.
    inoremap <expr><S-TAB>  pumvisible() ? "\<C-p>" : "\<C-h>"
'''

[[plugins]] # deoplete source for jedi
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
depends = 'deoplete.nvim'

[[plugins]] # deoplete source for c, cpp
repo = 'deoplete-plugins/deoplete-clang'
on_ft = ['c', 'cpp']
depends = 'deoplete.nvim'
hook_source = '''
    let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-8/lib/libclang.so'
    let g:deoplete#sources#clang#clang_header = '/usr/include/clang/8/include'
'''

[[plugins]] # deoplete source for vim
repo = 'Shougo/neco-vim'
on_ft = 'vim'
depends = 'deoplete.nvim'

[[plugins]] # deoplete source for javascript
repo = 'carlitux/deoplete-ternjs'
on_ft = 'javascript'
depends = 'deoplete.nvim'
hook_source = '''
    let g:deople#sources#ternjs#tern_bin = '/usr/bin/tern'
    let g:deoplete#sources#ternjs#timeout = 1
    let g:deoplete#sources#ternjs#types = 1
    let g:deoplete#sources#ternjs#depths = 1
    let g:deoplete#sources#ternjs#docs = 1
    let g:deoplete#sources#ternjs#filter = 0
    let g:deoplete#sources#ternjs#case_insensitive = 1
    let g:deoplete#sources#ternjs#guess = 0
    let g:deoplete#sources#ternjs#sort = 0
    let g:deoplete#sources#ternjs#expand_word_forward = 0
    let g:deoplete#sources#ternjs#omit_object_prototype = 0
    let g:deoplete#sources#ternjs#include_keywords = 1
    let g:deoplete#sources#ternjs#in_literal = 0

'''

[[plugins]]
repo ='kannokanno/previm'
on_ft = 'markdown'
hook_source = '''
    let g:previm_open_cmd = 'google-chrome'
'''
