[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # カーソル位置コンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定する
repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # コピーペースト革命
repo = 'ConradIrwin/vim-bracketed-paste'

[[plugins]] # カラースキーム革命
repo = 'flazz/vim-colorschemes'

[[plugins]] # コメントアウト革命
repo = 'tyru/caw.vim'
hook_add = '''
    " \cで行の先頭にコメントをつけたり外したりする
    nmap <Leader>c <Plug>(caw:hatpos:toggle)
    vmap <Leader>c <Plug>(caw:hatpos:toggle)
'''
